#!/bin/bash
exec 2>&1
export HOME=/home/bigcouch
exec chpst -u bigcouch /opt/bigcouch/bin/bigcouch

# increase the max. no of open files
# see https://leap.se/code/issues/4935 for details
ulimit -S -n 4096
ulimit -H -n 32768

